// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ3bxJYjidXzlF-Ue-dLLhHiQ5qkgfYhQ',
    appId: '1:823612926364:web:d4e08bb447166f864dc059',
    messagingSenderId: '823612926364',
    projectId: 'watch-app1-60ddd',
    authDomain: 'watch-app1-60ddd.firebaseapp.com',
    storageBucket: 'watch-app1-60ddd.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Cfstv0X5YRAxuHl9nQUK8slcVs4YaBA',
    appId: '1:823612926364:ios:e2c7886dc754bb184dc059',
    messagingSenderId: '823612926364',
    projectId: 'watch-app1-60ddd',
    storageBucket: 'watch-app1-60ddd.appspot.com',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ3bxJYjidXzlF-Ue-dLLhHiQ5qkgfYhQ',
    appId: '1:823612926364:web:b59283661657645b4dc059',
    messagingSenderId: '823612926364',
    projectId: 'watch-app1-60ddd',
    authDomain: 'watch-app1-60ddd.firebaseapp.com',
    storageBucket: 'watch-app1-60ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Cfstv0X5YRAxuHl9nQUK8slcVs4YaBA',
    appId: '1:823612926364:ios:e2c7886dc754bb184dc059',
    messagingSenderId: '823612926364',
    projectId: 'watch-app1-60ddd',
    storageBucket: 'watch-app1-60ddd.appspot.com',
    iosBundleId: 'com.example.watchApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi67As15cyFPWXy2WVBYzPY7md7nE6UPw',
    appId: '1:1060213988768:android:d6c4293afe531b4ac658c5',
    messagingSenderId: '1060213988768',
    projectId: 'watch-app-33a31',
    databaseURL: 'https://watch-app-33a31-default-rtdb.firebaseio.com',
    storageBucket: 'watch-app-33a31.appspot.com',
  );

}